version: 2
project_name: dexctl
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: dexctl
    binary: dexctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - id: dexctl
    builds:
      - dexctl
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}darwin-{{- else if eq .Os "linux" }}linux-{{- else if eq .Os "windows" }}windows-{{- end }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: dennismdejong
    name: dexctl